### PR TITLE
Added game controller rumble functionality

### PR DESCRIPTION
**Pull request by alexispaez**
Added game controller Has_Rumble and Rumble functions.

### CODE REVIEW

**Comment by Lucretia** [comment]
the .clang-format file seems to have been added by mistake. Can you put it into your gitignore file and remove it from the PR please.

**Comment by Lucretia** [comment]
Cheers. How about a [program](https://github.com/ada-game-framework/sdlada_test_progs) to test it, or is that a bit tricky?

**Comment by alexispaez** [comment]
I'll certainly have a look at it! Thanks!

**Comment by Lucretia** [comment]
Yeah, I've had something similar before due to nested crates, mine works, alr is supposed to build those files. I'm not sure how I got it to work. Just change the following line to this for now:

```
project-files = ["sdlada_test_progs.gpr"]
```

and remove ` "libraries.adb",` line from `sdlada_test_progs.gpr`.

**Comment by alexispaez** [comment]
Ok, It's working now, thanks. The idea is to make a program that will use
the functionality, right? It's not like unit testing or anything like that,
right?

**Comment by Lucretia** [comment]
Yeah, just a test program that shows off something, like the other programs in that repo. I have a steam controller (v1) I can test it with.

**Pull request merged**
